### ISSUE TITLE
Setup Issues

### ISSUE THREAD

**Issue by Longshotpro2** [lukalabs/cakechat#22]
I first tried the docker setup but it errored out and I just assumed that it was my fault since I haven't used docker before. Then I moved to the manual setup and it threw the same error.

While installing, the bdust_wheel for scipy errors which gives me:

- Failed building wheel for scipy
- Failed cleaning build dir for scipy
- Failed building wheel for scikit-learn

which then breaks the install with:
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Je8Y7m/scipy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-VPk4Mt-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-Je8Y7m/scipy/

**Comment by rodart** [comment]
Hi @Longshotpro2! It looks like scipy build problem on your machine. I'd recommend using docker, you can start it only with one command: https://github.com/lukalabs/cakechat#quick-start

Otherwise, you could have all these installation problems with scipy/numpy/theano/whatever external libs on your machine and you need to figure out the way how to install each one

**Comment by Longshotpro2** [comment]
I did a fresh install of the os, installed docker and then ran the quick-start. The first line exited with standard_init_linux.go:190: exec user process caused "exec format error"

which made the second line not work at all.

**Comment by rodart** [comment]
1) It's one-line command actually. It's formatted in two lines for better visual perception
2) Which OS do you use on your host machine?

**Comment by Longshotpro2** [comment]
I am using Raspbian, Debian Stretch.

**Comment by rodart** [comment]
I think that's the problem. I'd not recommend even try to run or train Cakechat model on Raspberry Pi (I guess you have it as you mention Raspbian) because the model is required heavy computations. Also, you'll have a ton of problems with libs installation as you have right now.

We tested cakechat on MacOS High Sierra, Ubuntu (14.04, 16.04) and Windows 10. You could try any of these, should work

**Comment by Longshotpro2** [comment]
Okay, the thought process was to train on paperspace after playing around with the sample model but implement on the pi or docker swarm.

**Comment by rodart** [comment]
For training model, you could try any cloud provider with Nvidia GPU VMs. But again, I really doubt that it's possible to launch a trained model on the pi.

**Comment by rodart** [comment]
@Longshotpro2 Do you have any other questions about cakechat setup?

**Comment by Longshotpro2** [comment]
No, not at this time. Thank you for your help!

**Comment by retallicka** [comment]
I have the same problem. I am using manual setup. I can't install Docker on this machine as I am using Windows 10 Home edition
