### ISSUE TITLE
How to improve the responses of the model?

### ISSUE THREAD

**Issue by sanjanaargula** [lukalabs/cakechat#37]

**Comment by sanjanaargula** [comment]
Even after training the model and compiling, when we do the testing with:

python tools/test_api.py -f 127.0.0.1 -p 8080 \
    -c "Hi, Eddie, what's up?" \
    -c "Not much, what about you?" \
    -c "Fine, thanks. Are you going to the movies tomorrow?"

It is giving the answer "Movies" or some other stuff like that. What can we do to improve the responses?

**Comment by nicolas-ivanov** [comment]
@sanjanaargula do you still have the question?

**Comment by sanjanaargula13** [comment]
Yes

**Comment by nicolas-ivanov** [comment]
Ok, but I don't see the description of the issue )

**Comment by sanjanaargula13** [comment]
Description: After I have compiled and trained the model, when I am starting server and client, 
My questions like "How are you?" "How was your day" or even a simple "Hi" renders weird responses like

"Movies" "Yes Eddie, but what much"

**Comment by nicolas-ivanov** [comment]
Apparently, you did not train your model enough or your model overfitted the data. 

How long did you train and how much train data do you have? Did you initialise your model with the provided trained weights?

**Comment by sanjanaargula13** [comment]
I followed the steps they gave. 

tools/download_model.py

bin/cakechat_server.py

**Comment by nicolas-ivanov** [comment]
Just checked the trained model, it looks fine to me:

![image](https://user-images.githubusercontent.com/2272790/46809716-c84b9900-cd77-11e8-856e-861163f2874c.png)

Model weights or index files might get messed up while you experimented with the model. Try running `tools/download_model.py` again and make sure that the following files have been updated:

* data/nn_models/cakechat_v1.3_processed_dialogs_gru_hd512_cdim128_drop0.2_encd2_decd2_il30_cs3_ansl32_lr1.0_gc5.0_learnemb
* data/w2v_models/train_processed_dialogs_window10_voc50000_vec128_sgTrue.bin
* data/tokens_index/t_idx_processed_dialogs.json

**Comment by sanjanaargula** [comment]
I am getting the following response when I am trying to train the model. In those three files you specified, the .bin file is not getting downloaded because of some AWS error.
![capture](https://user-images.githubusercontent.com/40475905/47257134-aeacfe80-d4a7-11e8-97d1-34c1353aeab8.PNG)

**Comment by nicolas-ivanov** [comment]
> I am getting the following response when I am trying to train the model.

You need to end the other process in order to release the file. Are you trying to train several models at the same time? If yes, don't do so. If no, there may be some process from your previous launch that didn't not stop correctly, system reboot should fix the issue.

**Comment by nicolas-ivanov** [comment]
In any case consider the following: 

1. Use a big corpus to train your model on. The one that is provided in the repo (`data/corpora_processed/train_processed_dialogs.txt`) is just a dummy sample to show the required structure of the document. Unfortunately for privacy reasons we can't provide the original corpus that was used for training the model. See [this answer](https://github.com/lukalabs/cakechat/issues/34#issuecomment-421365062) to get one of publicly available dialog corpora. You need to prepare the corpora so that it has the same structure, as the provided sample. After that you can replace (`data/corpora_processed/train_processed_dialogs.txt`) and start training.

2. When you run `python prepare_index_files.py` the script takes train corpus (`data/corpora_processed/train_processed_dialogs.txt`) and builds tokens index (`data/tokens_index/t_idx_processed_dialogs.json`), overwriting the original tokens index file. Since now you only have access to a dummy train corpus, this operation screws up the original tokens index file. Word2vec model name depends the vocabulary stored in tokens index files, that's why the proper w2v model can't be downloaded from AWS S3. We're gonna update the documentation to avoid this confusing behavior in future.
For now: don't run the command `python prepare_index_files.py` unless you 1. want to train your model from scratch 2. have large corpora to train your model on. To fix the problem, see [this answer](https://github.com/lukalabs/cakechat/issues/26#issuecomment-411091956).

3. Use GPU to train your model on, in this case it takes 5-10 days to train the model from scratch. One CPU will take years to do the same job.

**Comment by sanjanaargula** [comment]
> In any case consider the following:
> 
> 1. Use a big corpus to train your model on. The one that is provided in the repo (`data/corpora_processed/train_processed_dialogs.txt`) is just a dummy sample to show the required structure of the document. Unfortunately for privacy reasons we can't provide the original corpus that was used for training the model. See [this answer](https://github.com/lukalabs/cakechat/issues/34#issuecomment-421365062) to get one of publicly available dialog corpora. You need to prepare the corpora so that it has the same structure, as the provided sample. After that you can replace (`data/corpora_processed/train_processed_dialogs.txt`) and start training.
> 2. When you run `python prepare_index_files.py` the script takes train corpus (`data/corpora_processed/train_processed_dialogs.txt`) and builds tokens index (`data/tokens_index/t_idx_processed_dialogs.json`), overwriting the original tokens index file. Since now you only have access to a dummy train corpus, this operation screws up the original tokens index file. Word2vec model name depends the vocabulary stored in tokens index files, that's why the proper w2v model can't be downloaded from AWS S3. We're gonna update the documentation to avoid this confusing behavior in future.
>    For now: don't run the command `python prepare_index_files.py` unless you 1. want to train your model from scratch 2. have large corpora to train your model on. To fix the problem, see [this answer](https://github.com/lukalabs/cakechat/issues/26#issuecomment-411091956).
> 3. Use GPU to train your model on, in this case it takes 5-10 days to train the model from scratch. One CPU will take years to do the same job.

#2 suggestion worked perfectly. The program gave perfect replies as expected. Thanks a lot!

**Comment by nicolas-ivanov** [comment]
Great!
