### ISSUE TITLE
How to get only 1 sentence of answer?

### ISSUE THREAD

**Issue by hoanganhtuanfsoft** [lukalabs/cakechat#53]
When I input a question (single sentence), I have received a respond (with multi sentences) from my custom model. How to get an answer with only 1 sentence?
Thank you for helping!

**Comment by nicolas-ivanov** [comment]
Hello, @hoanganhtuanfsoft!
For a give context CakeChat model always outputs one answer, that indeed can include several sentences. For example:

```
Hey, how are you? → Hi! I'm doing great. What about you?
```
Is your question about splitting the answer into several grammatical sentences? Like returning only "Hi!" instead of "Hi! I'm doing great. What about you?"

```
Hey, how are you? → Hi!
```

If so, this postprocessing can be done using `nltk` package. Please see the following answer on stackoverflow: https://stackoverflow.com/a/37605851/1712419

You'll need to add the corresponding code after this line: https://github.com/lukalabs/cakechat/blob/master/cakechat/api/response.py#L46

**Comment by hoanganhtuanfsoft** [comment]
Oh. I see. I thought I can set the number of output sentences. 

> If so, this postprocessing can be done using nltk package. Please see the following answer on stackoverflow: https://stackoverflow.com/a/37605851/1712419

I know it. But I want to model can inference only 1 sentence without other processing. :D 

I built on 61 conversations with 50 epoch. I met bad result :( 
I can't get more data because of specific data.
