### ISSUE TITLE
When the training model is successfully restarted, the start-up service fails to find the model.

### ISSUE THREAD

**Issue by Spring1212** [lukalabs/cakechat#63]
The custom training model was successful, and an error occurred when running the python bin/cakechat_server.py command to start the service.
![TIM图片20190709163956](https://user-images.githubusercontent.com/50136775/60874364-7aae7f00-a26a-11e9-9128-c521308205ab.png)
The operating system is Centos7.

**Comment by nicolas-ivanov** [comment]
@Spring1212, the size of vocabulary that you are trying to use is only 26 tokens - not good. Apparently you rewrote the default vocabulary file by running `prepare_index_files.py`. See the corresponding section of our Readme for a fix guideline: https://github.com/lukalabs/cakechat#training-the-model-from-scratch

**Comment by Spring1212** [comment]
Is this due to too little training data?

**Comment by Spring1212** [comment]
Can adding training data avoid this problem?

**Comment by nicolas-ivanov** [comment]
> Is this due to too little training data?

You got a different index files because apparently you run `prepare_index_files.py` and it rewrote the original index files. Even if you had training data in abundance, running this script would still result in overwriting index files, so won't be able to use our pretrained model. 

If you just want to use our pretrained model without finetuning on you own data, you don't need to run `prepare_index_files.py` script. Restore the default index files following the link I send you in the previous message and run the server with our pretrained model after that. 

And in case you do want to tune our model or to train your own from scratch, please, read carefully the corresponding sections from our Readme: https://github.com/lukalabs/cakechat#training-the-model

**Comment by Spring1212** [comment]
According to the self-report file training model from scratch, every step of adding training data into the file is operated.
![AZZJT LIW5_4V$RH4WAHY`2](https://user-images.githubusercontent.com/50136775/60880248-de8a7500-a275-11e9-9829-35a61cd857ae.png)

**Comment by Spring1212** [comment]
Is this still a pre-training model?

**Comment by nicolas-ivanov** [comment]
Seems like I got the problem: the server is trying to use reverse model for `sampling_reranking` mode of generating answers and, I assume, you didn't train it.

Option 1: change `sampling_reranking` to `sampling` here: https://github.com/lukalabs/cakechat/blob/master/cakechat/api/config.py#L4

Option 2: run `python tools/train.py -r` to train reverse model.

In either case, please, note that you'll need to use a larger training set with larger vocabulary to get any meaningful results after training.
