### ISSUE TITLE
Dataset Format

### ISSUE THREAD

**Issue by 26hmkk** [lukalabs/cakechat#64]
When preparing for training, I was looking through the sample dataset;

`[{"text": "Hello", "condition": "neutral"}, {"text": "Oh, hi! :) How are you, my friend?", "condition": "joy"}, {"text": "Doing good", "condition": "neutral"}]`

Which phrase is being said by the model and which is manually typed by the user?

To me it looks of the form `[{USER STATEMENT}, {MODEL RESPONSE}, {USER AGAIN}]` 

But this doesn’t make sense to me. I would think the data should be formatted more like `[{MODEL STATEMENT}, {USER RESPONSE}, {MODEL AGAIN}]`?

Could someone help me clarify which party is intended to be saying which statement in the example and why it is in that order? Thanks.

**Comment by nicolas-ivanov** [comment]
In the training dataset all the phrases should belong to human speakers, since the goal for our chatbot is to learn how to mimic humans way of chatting. So the format for the dataset should look like:

```
[<speaker_1>, <speaker_2>, <speaker_1>, ...]
```
Note, that the number of phrases in one dialog can be arbitrary long, but no less than 2. For more details on how each dialog is transformed to training samples with predefined context length, see this comment: https://github.com/lukalabs/cakechat/issues/45#issuecomment-476618886

**Comment by 26hmkk** [comment]
Thanks for the response.

Just to reword a little, since this is for conversation, I'm wondering if in the format

`[<speaker_1>, <speaker_2>, <speaker_1>]`

**Comment by nicolas-ivanov** [comment]
Like both, since each dialog with three phrases [a, b, c]  will be transformed to the following several training samples:

```
X: [_, _, a] , Y: b 
X: [_, a, b] , Y: c
```
where X is a context, Y is response that model tries to mimic, and _ is an empty phrase that is used to unify the context length (3 in the example above).

If you want to mimic a specific person, one option is to feed only the dialogs with length 2, like [<speaker_1>, <speaker_2>], and the other option is to rewrite this function: https://github.com/lukalabs/cakechat/blob/master/cakechat/utils/dataset_loader.py#L116

**Comment by 26hmkk** [comment]
Thanks, this is very helpful. I think my issue is resolved.
